import React from "react";
import ReactDOM from "react-dom/client";

const resList = [
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "698272",
        name: "Maiz Mexican Kitchen",
        uuid: "af97c998-0199-48ab-8d24-2122cd4c2e36",
        city: "5",
        area: "BKC",
        totalRatingsString: "100+ ratings",
        cloudinaryImageId: "8fb434032fdce4f38d98fef761589c25",
        cuisines: ["Mexican", "Italian", "American"],
        tags: [],
        costForTwo: 60000,
        costForTwoString: "₹600 FOR TWO",
        deliveryTime: 29,
        minDeliveryTime: 29,
        maxDeliveryTime: 29,
        slaString: "29 MINS",
        lastMileTravel: 1.399999976158142,
        slugs: {
          restaurant: "maiz-mexican-kitchen-bandra-west-bandra-west",
          city: "mumbai",
        },
        cityState: "5",
        address:
          "OFFICE NO. 10, SWASTIK INDUSTRIAL ESTATE, VIDYANAGARI MARG, KALINA CST ROAD, SANTACRUZ EAST MUMBAI , Greater Mumbai Ward-H/E, Greater Mumbai, Maharashtra-400098",
        locality: "Kalina Cst Road",
        parentId: 11654,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        ribbon: [
          {
            type: "PROMOTED",
          },
        ],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 3500,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 3500,
          message: "",
          title: "Delivery Charge",
          amount: "3500",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID:
          "cid=7026673~p=16~eid=00000188-f808-f3cc-12ad-fcf800f7100d~srvts=1687788516300",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "1.3 kms",
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "40% OFF",
          subHeader: "UPTO ₹80",
          discountTag: "",
          headerTypeV2: 0,
        },
        sla: {
          restaurantId: "698272",
          deliveryTime: 29,
          minDeliveryTime: 29,
          maxDeliveryTime: 29,
          lastMileTravel: 1.399999976158142,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: true,
        avgRating: "4.3",
        totalRatings: 100,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "358147",
        name: "Meraki",
        uuid: "534603b2-56ae-41c1-922c-725b4d33edb9",
        city: "5",
        area: "Kurla",
        totalRatingsString: "5000+ ratings",
        cloudinaryImageId: "wmmzbfzsvrxc38x9tvho",
        cuisines: ["Chinese", "Burmese", "Thai", "Beverages", "Thalis"],
        tags: [],
        costForTwo: 50000,
        costForTwoString: "₹500 FOR TWO",
        deliveryTime: 30,
        minDeliveryTime: 30,
        maxDeliveryTime: 30,
        slaString: "30 MINS",
        lastMileTravel: 1,
        slugs: {
          restaurant: "meraki-scruz-bandra-east-scruz-bandra-east-2",
          city: "mumbai",
        },
        cityState: "5",
        address:
          "Shop no. 10/11, kasam Chunawlaa Compound, Shastri Nagar, Kalina, Near Bimsillah Hotel, Santacruz East       400029",
        locality: "Shastri Nagar",
        parentId: 2356,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 3500,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 3500,
          message: "",
          title: "Delivery Charge",
          amount: "3500",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "1 kms",
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "₹125 OFF",
          subHeader: "ABOVE ₹599",
          discountTag: "FLAT DEAL",
          headerTypeV2: 0,
        },
        sla: {
          restaurantId: "358147",
          deliveryTime: 30,
          minDeliveryTime: 30,
          maxDeliveryTime: 30,
          lastMileTravel: 1,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.2",
        totalRatings: 5000,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "372200",
        name: "New Lajawaab Seekh Corner",
        uuid: "d17d7cb9-a980-4515-b15d-3d75212457f8",
        city: "5",
        area: "Bhd Kurla Weight Bridge",
        totalRatingsString: "1000+ ratings",
        cloudinaryImageId: "wtjwh915fnytypbywvcs",
        cuisines: ["Indian"],
        tags: [],
        costForTwo: 20000,
        costForTwoString: "₹200 FOR TWO",
        deliveryTime: 28,
        minDeliveryTime: 28,
        maxDeliveryTime: 28,
        slaString: "28 MINS",
        lastMileTravel: 0.6000000238418579,
        slugs: {
          restaurant: "new-lajawaab-seekh-corner-kurla-kurla",
          city: "mumbai",
        },
        cityState: "5",
        address:
          "GALA NO 1,2,3, BHD KURLA WEIGHT BRIDGE LBS ROAD KURLA WEST MUMBAI 400070",
        locality: "Kurla",
        parentId: 147071,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 3500,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 3500,
          message: "",
          title: "Delivery Charge",
          amount: "3500",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "0.6 kms",
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "₹100 OFF",
          subHeader: "ABOVE ₹599",
          discountTag: "FLAT DEAL",
          headerTypeV2: 0,
        },
        sla: {
          restaurantId: "372200",
          deliveryTime: 28,
          minDeliveryTime: 28,
          maxDeliveryTime: 28,
          lastMileTravel: 0.6000000238418579,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.1",
        totalRatings: 1000,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "627565",
        name: "Sweet County Cake Shop",
        uuid: "27e7cbf3-0a30-4685-bc43-623a529365a8",
        city: "5",
        area: "Ghatkopar East",
        totalRatingsString: "50+ ratings",
        cloudinaryImageId: "d99d140b0983e6f10f85e9a58fd1057e",
        cuisines: ["Desserts", "Bakery", "Snacks"],
        tags: [],
        costForTwo: 20000,
        costForTwoString: "₹200 FOR TWO",
        deliveryTime: 35,
        minDeliveryTime: 35,
        maxDeliveryTime: 35,
        slaString: "35 MINS",
        lastMileTravel: 4.800000190734863,
        slugs: {
          restaurant: "sweet-county-ghatkopar-vikhroli-ghatkopar-vikhroli",
          city: "mumbai",
        },
        cityState: "5",
        address:
          "2/A, Prakash Building, RB Mehta Marg, MHADA Colony, Pant Nagar, Ghatkopar East, Mumbai, Maharashtra 400077, India",
        locality: "Pant Nagar",
        parentId: 338279,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        ribbon: [
          {
            type: "PROMOTED",
          },
        ],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 4500,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 4500,
          message: "",
          title: "Delivery Charge",
          amount: "4500",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID:
          "cid=7200984~p=19~eid=00000188-f808-f3cc-12ad-fcf900f71325~srvts=1687788516300",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "4.8 kms",
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "50% OFF",
          subHeader: "UPTO ₹100",
          discountTag: "",
          headerTypeV2: 0,
        },
        sla: {
          restaurantId: "627565",
          deliveryTime: 35,
          minDeliveryTime: 35,
          maxDeliveryTime: 35,
          lastMileTravel: 4.800000190734863,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: true,
        avgRating: "4.5",
        totalRatings: 50,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "82668",
        name: "The Belgian Waffle Co.",
        uuid: "81a57548-8c03-4f5d-95e0-4f32a060fa60",
        city: "5",
        area: "Santacruz East",
        totalRatingsString: "1000+ ratings",
        cloudinaryImageId: "gwfdgqjf5oymhegcvhvn",
        cuisines: ["Waffle", "Desserts", "Ice Cream", "Beverages"],
        tags: [],
        costForTwo: 20000,
        costForTwoString: "₹200 FOR TWO",
        deliveryTime: 31,
        minDeliveryTime: 31,
        maxDeliveryTime: 31,
        slaString: "31 MINS",
        lastMileTravel: 1.2999999523162842,
        slugs: {
          restaurant: "the-belgian-waffle-co-kalina-scruz-bandra-east",
          city: "mumbai",
        },
        cityState: "5",
        address:
          "No. 5, SUMIT ARTISTA, opp. AUDI SERVICE CENTER, Near BKC, KALINA, SANTACRUZ (E)Greater Mumbai, Maharashtra, 400059",
        locality: "Kalina",
        parentId: 2233,
        unserviceable: false,
        veg: true,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 3600,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 3600,
          message: "",
          title: "Delivery Charge",
          amount: "3600",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "1.2 kms",
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "20% OFF",
          subHeader: "UPTO ₹50",
          discountTag: "",
          headerTypeV2: 0,
        },
        sla: {
          restaurantId: "82668",
          deliveryTime: 31,
          minDeliveryTime: 31,
          maxDeliveryTime: 31,
          lastMileTravel: 1.2999999523162842,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.3",
        totalRatings: 1000,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "5956",
        name: "Veg Sutra",
        uuid: "3378460f-54ff-4829-abf4-f1cace1a7ead",
        city: "5",
        area: "Kurla",
        totalRatingsString: "10000+ ratings",
        cloudinaryImageId: "lbudaxadlhmchfq4jh32",
        cuisines: [
          "North Indian",
          "Chinese",
          "Pizzas",
          "Desserts",
          "Beverages",
        ],
        tags: [],
        costForTwo: 25000,
        costForTwoString: "₹250 FOR TWO",
        deliveryTime: 29,
        minDeliveryTime: 29,
        maxDeliveryTime: 29,
        slaString: "29 MINS",
        lastMileTravel: 1.2000000476837158,
        slugs: {
          restaurant: "veg-sutra-scruz-bandra-east",
          city: "mumbai",
        },
        cityState: "5",
        address:
          "Shop 3, A 176, Belgrami Road & LBS Marg Junction, Near Bandra Kurla Complex, Mumbai400070",
        locality: "BKC",
        parentId: 10928,
        unserviceable: false,
        veg: true,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 3500,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 3500,
          message: "",
          title: "Delivery Charge",
          amount: "3500",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "1.2 kms",
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "30% OFF",
          subHeader: "UPTO ₹75",
          discountTag: "",
          headerTypeV2: 0,
        },
        sla: {
          restaurantId: "5956",
          deliveryTime: 29,
          minDeliveryTime: 29,
          maxDeliveryTime: 29,
          lastMileTravel: 1.2000000476837158,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.3",
        totalRatings: 10000,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "391816",
        name: "Louis Burger",
        uuid: "1319ca4c-17c3-4741-ab37-ceb376f54b05",
        city: "5",
        area: "Santacruz Bandra east",
        totalRatingsString: "1000+ ratings",
        cloudinaryImageId: "19d3d352cc815b9d88b22617b41fa97b",
        cuisines: ["Burgers", "Fast Food", "Beverages"],
        tags: [],
        costForTwo: 60000,
        costForTwoString: "₹600 FOR TWO",
        deliveryTime: 29,
        minDeliveryTime: 29,
        maxDeliveryTime: 29,
        slaString: "29 MINS",
        lastMileTravel: 1.399999976158142,
        slugs: {
          restaurant: "louis-burger-trade-centre-scruz-bandra-east",
          city: "mumbai",
        },
        cityState: "5",
        address:
          "Star Awas, G4-A, Ground Floor, Trade Centre, Bandra East, Mumbai, Maharashtra 400051",
        locality: "Trade Centre",
        parentId: 22485,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        ribbon: [
          {
            type: "PROMOTED",
          },
        ],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 3600,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 3600,
          message: "",
          title: "Delivery Charge",
          amount: "3600",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID:
          "cid=7136666~p=22~eid=00000188-f808-f3cc-12ad-fcfa00f7163c~srvts=1687788516300",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "1.3 kms",
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "20% OFF",
          subHeader: "UPTO ₹50",
          discountTag: "",
          headerTypeV2: 0,
        },
        sla: {
          restaurantId: "391816",
          deliveryTime: 29,
          minDeliveryTime: 29,
          maxDeliveryTime: 29,
          lastMileTravel: 1.399999976158142,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: true,
        avgRating: "4.3",
        totalRatings: 1000,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "338372",
        name: "Merwans Cake Stop",
        uuid: "d461ead0-469f-4d17-b9bd-ff591a7164a9",
        city: "5",
        area: "Kurla West",
        totalRatingsString: "1000+ ratings",
        cloudinaryImageId: "c2ootw6sg891x1b8ro6n",
        cuisines: ["Desserts", "Bakery"],
        tags: [],
        costForTwo: 30000,
        costForTwoString: "₹300 FOR TWO",
        deliveryTime: 24,
        minDeliveryTime: 24,
        maxDeliveryTime: 24,
        slaString: "24 MINS",
        lastMileTravel: 1.100000023841858,
        slugs: {
          restaurant: "merwans-cake-stop-kurla-kurla",
          city: "mumbai",
        },
        cityState: "5",
        address:
          "SHOP NO.3, GRD FLOOR, NEW DWARAKAPURI CHS LTD., LBS MARG, KURLA(W), MUMBAI - 400070, District - Greater Mumbai, STATE - Maharashtra - 400070",
        locality: "Kurla",
        parentId: 135373,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 3500,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 3500,
          message: "",
          title: "Delivery Charge",
          amount: "3500",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "1.1 kms",
        hasSurge: false,
        sla: {
          restaurantId: "338372",
          deliveryTime: 24,
          minDeliveryTime: 24,
          maxDeliveryTime: 24,
          lastMileTravel: 1.100000023841858,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.4",
        totalRatings: 1000,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "366927",
        name: "Taj King Shawarma",
        uuid: "26cdd7f2-7037-47b3-ac0f-e6c6db511716",
        city: "5",
        area: "Kurla",
        totalRatingsString: "1000+ ratings",
        cloudinaryImageId: "yacdchtguervnbremc5g",
        cuisines: ["Indian"],
        tags: [],
        costForTwo: 20000,
        costForTwoString: "₹200 FOR TWO",
        deliveryTime: 24,
        minDeliveryTime: 24,
        maxDeliveryTime: 24,
        slaString: "24 MINS",
        lastMileTravel: 0.699999988079071,
        slugs: {
          restaurant: "taj-king-shawarma-kurla-kurla",
          city: "mumbai",
        },
        cityState: "5",
        address: "Shop 4, Near Kurla Weigst, Vridge Kurla, Mumbai",
        locality: "Near Kurla Weigst",
        parentId: 200121,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 3500,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 3500,
          message: "",
          title: "Delivery Charge",
          amount: "3500",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "0.6 kms",
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "₹20 OFF",
          subHeader: "",
          discountTag: "FLAT DEAL",
          headerTypeV2: 0,
        },
        sla: {
          restaurantId: "366927",
          deliveryTime: 24,
          minDeliveryTime: 24,
          maxDeliveryTime: 24,
          lastMileTravel: 0.699999988079071,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.1",
        totalRatings: 1000,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "66490",
        name: "Punjab Grill",
        uuid: "42e70642-e417-496e-a777-43a8ffd2324f",
        city: "5",
        area: "Bandra Kurla Complex",
        totalRatingsString: "1000+ ratings",
        cloudinaryImageId: "geb28dl0uilx6exkmapg",
        cuisines: ["North Indian", "Kebabs", "Biryani", "Mughlai"],
        tags: [],
        costForTwo: 90000,
        costForTwoString: "₹900 FOR TWO",
        deliveryTime: 38,
        minDeliveryTime: 38,
        maxDeliveryTime: 38,
        slaString: "38 MINS",
        lastMileTravel: 2.5999999046325684,
        slugs: {
          restaurant: "punjab-grill-the-capital-scruz-bandra-east",
          city: "mumbai",
        },
        cityState: "5",
        address:
          "G-5, The Capital, G Block BKC, Bandra Kurla Complex, Bandra (E), Mumbai, Maharashtra 400098",
        locality: "Bandra Kurla Complex",
        parentId: 734,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        ribbon: [
          {
            type: "PROMOTED",
          },
        ],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 3600,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 3600,
          message: "",
          title: "Delivery Charge",
          amount: "3600",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID:
          "cid=6954677~p=25~eid=00000188-f808-f3cc-12ad-fcfb00f71950~srvts=1687788516300",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "2.5 kms",
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "₹125 OFF",
          subHeader: "ABOVE ₹249",
          discountTag: "FLAT DEAL",
          headerTypeV2: 0,
        },
        sla: {
          restaurantId: "66490",
          deliveryTime: 38,
          minDeliveryTime: 38,
          maxDeliveryTime: 38,
          lastMileTravel: 2.5999999046325684,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: true,
        avgRating: "4.1",
        totalRatings: 1000,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "12434",
        name: "J.J. Jalebi",
        uuid: "5e1d9e3c-e122-48c2-b441-416d140bf962",
        city: "5",
        area: "Mumbai",
        totalRatingsString: "10000+ ratings",
        cloudinaryImageId: "mb5wiw7mk3yifcgf1g5j",
        cuisines: ["Desserts", "Sweets"],
        tags: [],
        costForTwo: 10000,
        costForTwoString: "₹100 FOR TWO",
        deliveryTime: 20,
        minDeliveryTime: 20,
        maxDeliveryTime: 20,
        slaString: "20 MINS",
        lastMileTravel: 0.6000000238418579,
        slugs: {
          restaurant: "jj-jalebi-lbs-marg-kurla",
          city: "mumbai",
        },
        cityState: "5",
        address:
          "JJ Jalebi, LBS Marg, Opposite Kalpana Theatre, Kurla West, Mumbai- 400070",
        locality: "LBS Marg",
        parentId: 247826,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 3500,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 3500,
          message: "",
          title: "Delivery Charge",
          amount: "3500",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "0.6 kms",
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "10% OFF",
          subHeader: "UPTO ₹40",
          discountTag: "",
          headerTypeV2: 0,
        },
        sla: {
          restaurantId: "12434",
          deliveryTime: 20,
          minDeliveryTime: 20,
          maxDeliveryTime: 20,
          lastMileTravel: 0.6000000238418579,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.0",
        totalRatings: 10000,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "111518",
        name: "Kurla Juicy Hut",
        uuid: "e074233a-b11d-480a-9640-457b279d3f6c",
        city: "5",
        area: "Kurla West",
        totalRatingsString: "5000+ ratings",
        cloudinaryImageId: "s6fhwzl0tss0vgrqvcid",
        cuisines: ["Beverages", "Desserts"],
        tags: [],
        costForTwo: 30000,
        costForTwoString: "₹300 FOR TWO",
        deliveryTime: 30,
        minDeliveryTime: 30,
        maxDeliveryTime: 30,
        slaString: "30 MINS",
        lastMileTravel: 0.6000000238418579,
        slugs: {
          restaurant: "kurla-juicy-hut-near-kalpana-cinema-kurla",
          city: "mumbai",
        },
        cityState: "5",
        address:
          "Shop 4, 168 L.B.S. Marg, Beside Salman Chambers, Near Kalpana Cinema, Kurla, Mumbai",
        locality: "Kurla",
        parentId: 121989,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 3500,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 3500,
          message: "",
          title: "Delivery Charge",
          amount: "3500",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "0.6 kms",
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "10% OFF",
          subHeader: "ABOVE ₹700",
          discountTag: "FLAT DEAL",
          headerTypeV2: 0,
        },
        sla: {
          restaurantId: "111518",
          deliveryTime: 30,
          minDeliveryTime: 30,
          maxDeliveryTime: 30,
          lastMileTravel: 0.6000000238418579,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.0",
        totalRatings: 5000,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "406314",
        name: "Cafe Quba",
        uuid: "d644e013-bfd3-4548-8d23-dca0b12ae6df",
        city: "5",
        area: "Chembur",
        totalRatingsString: "1000+ ratings",
        cloudinaryImageId: "w3qkr89mrliplzwjlyq2",
        cuisines: ["Chinese", "Indian", "North Indian"],
        tags: [],
        costForTwo: 40000,
        costForTwoString: "₹400 FOR TWO",
        deliveryTime: 36,
        minDeliveryTime: 36,
        maxDeliveryTime: 36,
        slaString: "36 MINS",
        lastMileTravel: 5,
        slugs: {
          restaurant: "cafe-quba-chembur-chembur",
          city: "mumbai",
        },
        cityState: "5",
        address:
          "Shop no 30, part no 1, new gautam nagar, p l lokhande marg, govandi ,Mumbai - 400043",
        locality: "New Gautam Nagar",
        parentId: 53961,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        ribbon: [
          {
            type: "PROMOTED",
          },
        ],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 6000,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 6000,
          message: "",
          title: "Delivery Charge",
          amount: "6000",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID:
          "cid=7168214~p=28~eid=00000188-f808-f3cc-12ad-fcfc00f71c28~srvts=1687788516300",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "5 kms",
        hasSurge: false,
        sla: {
          restaurantId: "406314",
          deliveryTime: 36,
          minDeliveryTime: 36,
          maxDeliveryTime: 36,
          lastMileTravel: 5,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: true,
        avgRating: "4.1",
        totalRatings: 1000,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "47833",
        name: "Persian Darbar",
        uuid: "5b5565d3-b714-47d3-8251-c6dd59c79699",
        city: "5",
        area: "Bandra Kurla Complex",
        totalRatingsString: "10000+ ratings",
        cloudinaryImageId: "79f013330e23a4f1bcb5262db7a7fc26",
        cuisines: ["Indian", "Chinese"],
        tags: [],
        costForTwo: 110000,
        costForTwoString: "₹1100 FOR TWO",
        deliveryTime: 35,
        minDeliveryTime: 35,
        maxDeliveryTime: 35,
        slaString: "35 MINS",
        lastMileTravel: 1.100000023841858,
        slugs: {
          restaurant: "persian-darbar-kurla-w-kurla",
          city: "mumbai",
        },
        cityState: "5",
        address:
          "SHOP NO.17,KANAKIA ZILLON BLDG,F WING Z6, L.B.S.ROAD,KURLA WEST NEAR KURLA BUS DepotEPOT,MUMBAI400070",
        locality: "",
        parentId: 711,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 3500,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 3500,
          message: "",
          title: "Delivery Charge",
          amount: "3500",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "1.1 kms",
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "₹150 OFF",
          subHeader: "ABOVE ₹999",
          discountTag: "FLAT DEAL",
          headerTypeV2: 0,
        },
        sla: {
          restaurantId: "47833",
          deliveryTime: 35,
          minDeliveryTime: 35,
          maxDeliveryTime: 35,
          lastMileTravel: 1.100000023841858,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.0",
        totalRatings: 10000,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "466304",
        name: "AL Zaika Dhaba",
        uuid: "7e4e2d70-877e-4f0a-947e-0885b8dc8db1",
        city: "5",
        area: "Kurla",
        totalRatingsString: "100+ ratings",
        cloudinaryImageId: "dp8jwzfgncapmekjgog6",
        cuisines: [
          "Indian",
          "Chinese",
          "Thalis",
          "Biryani",
          "Seafood",
          "Tandoor",
        ],
        tags: [],
        costForTwo: 30000,
        costForTwoString: "₹300 FOR TWO",
        deliveryTime: 43,
        minDeliveryTime: 43,
        maxDeliveryTime: 43,
        slaString: "43 MINS",
        lastMileTravel: 0.6000000238418579,
        slugs: {
          restaurant: "al-zaika-dhaba-kurla-kurla",
          city: "mumbai",
        },
        cityState: "5",
        address:
          "169, L.B.S. MARG, AGRA ROAD, NEAR KALPANA TALKIES, KURLA WEST MUMBAI-400070, Kurla Gaon, Greater Mumbai Ward-L, Greater Mumbai, Maharashtra - 400070",
        locality: "Near Kalpana Talkies",
        parentId: 280050,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 3500,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 3500,
          message: "",
          title: "Delivery Charge",
          amount: "3500",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "0.6 kms",
        hasSurge: false,
        sla: {
          restaurantId: "466304",
          deliveryTime: 43,
          minDeliveryTime: 43,
          maxDeliveryTime: 43,
          lastMileTravel: 0.6000000238418579,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.1",
        totalRatings: 100,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
];

const Header = () => {
  return (
    <section className="border">
      <div className="header container">
        <div className="logo__container">
          <img
            className="logo"
            src="https://www.logodesign.net/logo/smoking-burger-with-lettuce-3624ld.png"
          />
        </div>
        <nav>
          <ul className="nav__list">
            <li>Home</li>
            <li>About us</li>
            <li>Contact us</li>
            <li>Cart</li>
          </ul>
        </nav>
      </div>
    </section>
  );
};

const RestaurantCard = ({ resData }) => {
  const {
    name,
    cloudinaryImageId,
    costForTwo,
    cuisines,
    avgRating,
    deliveryTime,
  } = resData.data.data;

  return (
    <div
      className="res__card"
      style={{
        backgroundColor: "#f0f0f0",
      }}
    >
      <img
        className="res__img"
        src={`https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/${cloudinaryImageId}`}
        alt="res__logo"
      />
      <h5 style={{ color: "red" }}> ₹{costForTwo / 100} FOR TWO</h5>
      <h3>{name}</h3>
      <h4> {cuisines.join(", ")}</h4>
      <h5>{avgRating}⭐</h5>
      <h5>{deliveryTime} minutes</h5>
    </div>
  );
};

const Body = () => {
  return (
    <section className="container ">
      <div className="search">Search</div>
      <div className="res__container  ">
        {resList.map((restaurant) => (
          <RestaurantCard key={restaurant.data.data.id} resData={restaurant} />
        ))}
      </div>
    </section>
  );
};

const AppLayoutComponent = () => {
  return (
    <div className="app  ">
      <Header />
      <Body />
    </div>
  );
};
const root = ReactDOM.createRoot(document.getElementById("root"));

root.render(<AppLayoutComponent />);
